### ISSUE TITLE
Change Refresh-Rate of the script?

### ISSUE THREAD

**Issue by Stogie87** [ddomnik/nbbot#2]
Hi there,
thank you very much for the script.
Is there any chance to change the script refresh rate to 30 or 15 seconds?

**Comment by ddomnik** [comment]
Thanks for the reply. A refresh of 60 seconds is more than enough, considering there are bots that check only in a 5 minutes interval. 
Nevertheless, there will be a new release soon which only uses NVIDIA's API, as it seems it's more reliable than nbbs site.
An option to select the refresh rate may be added to that release.

**Comment by Stogie87** [comment]
Thanks for your Feedback.
Nice to hear about the upcoming update.
I always thought the telegram and discord bots provide a live update if new graphic cards are in stock...

**Comment by ddomnik** [comment]
Issue fixed in new release. https://github.com/ddomnik/nbbot/releases/tag/v1.0.0
