### ISSUE TITLE
The RTX 3060Ti is missing

### ISSUE THREAD

**Issue by 3xorcist** [ddomnik/nbbot#3]
Hi!
First of all, I would like to thank you for the slim application.
When I ran it I noticed that the -3060ti option is not included.
It's a bit of a shame as this is the FE card with the best price-performance ratio.

**Comment by ddomnik** [comment]
Thanks. The 3050 and 3060ti will be added with the next release.

**Comment by ddomnik** [comment]
Issue fixed in new release. https://github.com/ddomnik/nbbot/releases/tag/v1.0.0
